services:
  - type: web
    name: url-summary
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    repo: https://github.com/yyosshu/url-summary.git
    branch: main